version: "3"

server:
  command: "php worker.php"
  logs:
    mode: production
    level: warn
    output: stderr

http:
  address: 0.0.0.0:81
  access_logs: false
  raw_body: false
  pool:
    num_workers: 10
    debug: false
  middleware: ["headers"]
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600